import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ui/shared/NavBar";
import Footer from "@/components/ui/shared/Footer";
import Header from "@/components/ui/shared/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Header></Header> */}
        <Navbar></Navbar>
        <container className="min-h-screen">{children}</container>
        <Footer></Footer>
        </body>
    </html>
  );
}
